[package]
name = "async_scoped_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-scoped = "0.7.1"
tokio = { version = "1.33.0", features = ["full"] }
