[package]
name = "tokio_select"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.*" }
tokio = {version = "1.*", features = ["full"] }
tokio-stream = {version = "0.1.14", features = ["full"] }
